### ISSUE TITLE
Create Semantic Search Engine for the CICERO dataset

### ISSUE THREAD

**Issue by vcalderon2009** [Maven-Building-LLMS-into-Production/Cicero-LLM-Synthesizer#4]
## Description

Create a module that generates a Semantic Search model using the embeddings from the CICERO dataset, as generated in #3 .

**Comment by FloweryScythe13** [comment]
## Requirement Specifications: 

Input Dataset: `df_embed_out2.csv`, which includes both raw article contents and GPT-generated article summaries. 

Want to know the cosine similarity between article summaries and input query. 

Create a Semantic Search Engine class & model. In the Semantic Search Engine class, have a method create the embedding for the full input dataset. 
Make column selection and other details for creating the embedding parameterized. Follow good OOP design principles. Refer to module 4 Hotel Summarizer SemanticSearchEngine class for reference.
